{
 "title": "Application Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "App Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".*todolist-backend.*\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "count(container_last_seen{name=~\".*todolist-frontend.*\"})",
     "legendFormat": "Frontend"
    }
   ]
  },
  {
   "title": "API Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"todolist-backend\"}[5m])",
     "legendFormat": "{{method}} {{route}} - {{status_code}}"
    }
   ]
  },
  { "title": "Container Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"todolist-backend\"}[5m])) * 100",
     "legendFormat": "Backend CPU"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"todolist-frontend\"}[5m])) * 100",
     "legendFormat": "Frontend CPU"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".*todolist-backend.*\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".*todolist-frontend.*\"})",
     "legendFormat": "Frontend"
    }
   ]
  },
  { "title": "API Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "API Latency P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket{job=\"todolist-backend\"}[5m])) by (le))",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_ms_bucket{job=\"todolist-backend\"}[5m])) by (le))",
     "legendFormat": "P50 Latency"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "description": "Loki",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=~\"todolist-backend|todolist-frontend\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "App Logs",
   "type": "logs",
   "description": "Loki Logs Panel ",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"todolist-backend\"}",
     "legendFormat": "Backend"
    },
    {
     "direction": "backward",
     "expr": "{container=\"todolist-frontend\"}",
     "legendFormat": "Frontend"
    }
   ]
  }
 ]
}