{
 "title": "Infrastructure Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"node-exporter:9100\"}",
     "legendFormat": "EC2 Medium"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=\"10.0.1.7:9100\"}",
     "legendFormat": "DB EC2"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"} / node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"})) * 100",
     "legendFormat": "EC2 Medium Memory"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"10.0.1.7:9100\"} / node_memory_MemTotal_bytes{instance=\"10.0.1.7:9100\"})) * 100",
     "legendFormat": "DB EC2"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"node-exporter:9100\"}[5m])) * 100)",
     "legendFormat": "EC2 Medium CPU"
    },
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.0.1.7:9100\"}[5m])) * 100)",
     "legendFormat": "DB EC2 CPU"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"node-exporter:9100\"} / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"node-exporter:9100\"}) * 100)",
     "legendFormat": "EC2 Medium Disk"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"10.0.1.7:9100\"} / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"10.0.1.7:9100\"}) * 100)",
     "legendFormat": "DB EC2 Disk"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "EC2 Medium Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"10.0.1.7:9100\"} - node_memory_MemAvailable_bytes{instance=\"10.0.1.7:9100\"}\n",
     "legendFormat": "DB EC2 Used"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"node-exporter:9100\"}[5m])) * 100)",
     "legendFormat": "EC2 Medium CPU"
    },
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"10.0.1.7:9100\"}[5m])) * 100)",
     "legendFormat": "DB EC2 CPU"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\", instance=\"node-exporter:9100\"}[5m])",
     "legendFormat": "EC2 Medium In"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\", instance=\"node-exporter:9100\"}[5m])",
     "legendFormat": "EC2 Medium Out"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\", instance=\"10.0.1.7:9100\"}[5m])",
     "legendFormat": "DB EC2 In"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\", instance=\"10.0.1.7:9100\"}[5m])",
     "legendFormat": "DB EC2 Out"
    }
   ]
  }
 ]
}